const MODEL_NAMES = {
  "sonnet-4-5": "Sonnet 4.5",
  "haiku-4-5": "Haiku 4.5",
  "gpt-5-4-mini": "GPT-5.4 mini",
  "gpt-5-4-nano": "GPT-5.4 nano",
};

const PRICING = {
  "sonnet-4-5": {
    inputCost: "0.000003000",
    inputCaching: "0.000003750",
    outputCost: "0.000015000",
    outputCaching: "0.000000300",
  },
  "haiku-4-5": {
    inputCost: "0.000001000",
    inputCaching: "0.00000125",
    outputCost: "0.000005000",
    outputCaching: "0.000000100",
  },
  "gpt-5-4-mini": {
    inputCost: "0.000000750",
    inputCaching: "0.000000750",
    outputCost: "0.000004500",
    outputCaching: "0.000000075",
  },
  "gpt-5-4-nano": {
    inputCost: "0.000000200",
    inputCaching: "0.000000200",
    outputCost: "0.000001250",
    outputCaching: "0.000000020",
  },
};

const PARAM_HINTS = {
  "invoices-day":
    "How many invoice PDFs you expect to process on a typical working day. Used to estimate monthly volume.",
  "working-days":
    "Number of working days per month in your estimate (for example 25). Multiplied by daily invoice count.",
  "invoices-monthly":
    "Total invoices processed per month for this scenario. Calculated from daily volume × working days.",
  "document-size-tokens":
    "Average token count of one PDF after text extraction. Added to input tokens and affects caching cost.",
  "document-pages":
    "Approximate page count per document for reference. Not used in cost calculations.",
  "fields-total":
    "Total number of extraction fields across mandatory and optional columns combined.",
  model:
    "LLM used for this column. Determines per-token prices in the Pricing table and all cost rows below.",
  "fields-number":
    "How many fields this column extracts per document. Set to 0 to disable the column and exclude it from totals.",
  "input-cost":
    "Standard input price per token: Anthropic base input, or OpenAI input on the first (uncached) pass.",
  "input-caching":
    "Anthropic: price to write content into the 5-minute prompt cache. OpenAI has no separate cache-write fee.",
  "output-cost": "Price per token generated by the model in the response (structured output and thinking).",
  "output-caching":
    "Price to read previously cached input: Anthropic cache read, or OpenAI cached input rate.",
  "so-tokens-per-group":
    "Tokens consumed by the structured-output (SO) schema sent with each group prompt.",
  "so-total-tokens":
    "Total SO schema tokens for all groups in this column (SO tokens per group × Groups).",
  "prompt-size":
    "Fixed instruction or system prompt size in tokens, sent again with every group request.",
  "grouping-factor":
    "Maximum number of fields processed in a single LLM group. Larger groups mean fewer API calls.",
  groups:
    "Number of prompt groups required to cover all fields in this column (rounded up).",
  "input-total-tokens":
    "Total input tokens per document for this column: group SO tokens plus document text (once per PDF).",
  "thinking-budget-per-prompt":
    "Internal reasoning tokens reserved per group when extended thinking is enabled.",
  "thinking-budget-total":
    "Total thinking tokens across all groups in this column.",
  "so-output-per-field":
    "Expected output tokens produced per extracted field in structured output.",
  "so-output-total":
    "Total structured output tokens for all fields (per field × grouping × groups).",
  "output-total-tokens":
    "All output tokens per document for this column: thinking plus structured output.",
  "one-time-input":
    "Per-document cost of first-pass input: Anthropic cache write, or OpenAI uncached input (document + prompts).",
  "prompt-input":
    "Per-document cost of sending the fixed prompt with each group at base input price (Anthropic only).",
  "cached-input":
    "Per-document cost of reading cached document and schema content on subsequent groups.",
  "output-cost-doc":
    "Per-document LLM output cost based on total output tokens and the model output rate.",
  "total-cost-per-document":
    "Sum of all per-document LLM input and output cost lines for this column.",
  "input-cost-total":
    "Monthly input-side LLM cost: all per-document input lines multiplied by invoices per month.",
  "output-cost-monthly":
    "Monthly output LLM cost: output cost per document multiplied by invoices per month.",
  "ocr-cost":
    "Estimated OCR cost per document. Counted once per PDF when both columns are active.",
  "total-cost":
    "Monthly total for this column: input cost total, output cost monthly, and OCR where applicable.",
};

function initParamHints() {
  document.querySelectorAll("[data-param-hint]").forEach((rowHeader) => {
    if (rowHeader.querySelector(".param-hint")) return;

    const key = rowHeader.dataset.paramHint;
    const text = PARAM_HINTS[key];
    if (!text) return;

    const hint = document.createElement("span");
    hint.className = "formula-hint param-hint";
    hint.setAttribute("aria-label", "Parameter description");
    hint.innerHTML = `?<span class="formula-tooltip param-tooltip">${text}</span>`;
    rowHeader.appendChild(hint);
  });
}

const invoicesDay = document.getElementById("invoices-day");
const workingDays = document.getElementById("working-days");
const documentSizeTokens = document.getElementById("document-size-tokens");
const soTokensPerGroup = document.getElementById("so-tokens-per-group");
const promptSizeTokens = document.getElementById("prompt-size-tokens");
const thinkingBudgetPerPrompt = document.getElementById(
  "thinking-budget-per-prompt"
);
const mandatorySoOutputTokensPerField = document.getElementById(
  "mandatory-so-output-tokens-per-field"
);
const optionalSoOutputTokensPerField = document.getElementById(
  "optional-so-output-tokens-per-field"
);
const mandatoryGroupingFactor = document.getElementById(
  "mandatory-grouping-factor"
);
const optionalGroupingFactor = document.getElementById(
  "optional-grouping-factor"
);
const mandatoryModel = document.getElementById("mandatory-model");
const optionalModel = document.getElementById("optional-model");
const mandatoryFields = document.getElementById("mandatory-fields");
const optionalFields = document.getElementById("optional-fields");
const mandatoryEstimatedOcrCost = document.getElementById(
  "mandatory-estimated-ocr-cost"
);
const optionalEstimatedOcrCost = document.getElementById(
  "optional-estimated-ocr-cost"
);

function updateColumnVisibility() {
  const mandatory = Number(mandatoryFields.value) || 0;
  const optional = Number(optionalFields.value) || 0;

  document.querySelectorAll('[data-column="mandatory"]').forEach((cell) => {
    cell.hidden = mandatory === 0;
  });

  document.querySelectorAll('[data-column="optional"]').forEach((cell) => {
    cell.hidden = optional === 0;
  });
}

function updateModelTableHeaders(tableId, headerAttr) {
  const models = {
    mandatory: mandatoryModel.value,
    optional: optionalModel.value,
  };

  document
    .querySelectorAll(`#${tableId} [${headerAttr}]`)
    .forEach((cell) => {
      cell.textContent = MODEL_NAMES[models[cell.dataset.column]];
    });
}

function updatePricingTable() {
  const models = {
    mandatory: mandatoryModel.value,
    optional: optionalModel.value,
  };

  updateModelTableHeaders("pricing-table", "data-pricing-header");

  document
    .querySelectorAll("#pricing-table [data-pricing]")
    .forEach((cell) => {
      const column = cell.dataset.column;
      const key = cell.dataset.pricing;
      cell.textContent = formatCost(Number(PRICING[models[column]][key]));
    });
}

function getFieldCount(column) {
  return column === "mandatory"
    ? Number(mandatoryFields.value) || 0
    : Number(optionalFields.value) || 0;
}

function columnReceivesDocumentSize(column) {
  const mandatory = Number(mandatoryFields.value) || 0;
  const optional = Number(optionalFields.value) || 0;
  if (mandatory > 0) return column === "mandatory";
  if (optional > 0) return column === "optional";
  return false;
}

function getOcrCostForColumn(column) {
  const mandatory = Number(mandatoryFields.value) || 0;
  const optional = Number(optionalFields.value) || 0;
  const mandatoryOcr = Number(mandatoryEstimatedOcrCost.value) || 0;
  const optionalOcr = Number(optionalEstimatedOcrCost.value) || 0;

  if (mandatory === 0 && optional === 0) return 0;
  if (mandatory > 0 && optional > 0) {
    return column === "mandatory" ? mandatoryOcr : 0;
  }
  if (column === "mandatory" && mandatory > 0) return mandatoryOcr;
  if (column === "optional" && optional > 0) return optionalOcr;
  return 0;
}

function calcGroups(fieldsCount, factor) {
  const factorNum = Number(factor) || 0;
  if (factorNum === 0) return 0;
  return Math.ceil((Number(fieldsCount) || 0) / factorNum);
}

function getColumnGroups() {
  const mandatory = Number(mandatoryFields.value) || 0;
  const optional = Number(optionalFields.value) || 0;

  return {
    mandatory: calcGroups(mandatory, mandatoryGroupingFactor.value),
    optional: calcGroups(optional, optionalGroupingFactor.value),
    mandatoryFields: mandatory,
    optionalFields: optional,
  };
}

function updateInputTokensTable() {
  const { mandatory, optional, mandatoryFields: mFields, optionalFields: oFields } =
    getColumnGroups();

  updateModelTableHeaders("input-tokens-table", "data-input-tokens-header");

  const soPerGroup = Number(soTokensPerGroup.value) || 0;
  const documentSize = Number(documentSizeTokens.value) || 0;

  const mandatorySoTotal = mFields > 0 ? soPerGroup * mandatory : 0;
  const optionalSoTotal = oFields > 0 ? soPerGroup * optional : 0;
  const mandatoryDocSize =
    mFields > 0 && columnReceivesDocumentSize("mandatory") ? documentSize : 0;
  const optionalDocSize =
    oFields > 0 && columnReceivesDocumentSize("optional") ? documentSize : 0;

  document.querySelector('[data-groups="mandatory"]').textContent =
    mFields > 0 ? mandatory : 0;
  document.querySelector('[data-groups="optional"]').textContent =
    oFields > 0 ? optional : 0;
  document.querySelector('[data-so-total="mandatory"]').textContent =
    mandatorySoTotal;
  document.querySelector('[data-so-total="optional"]').textContent =
    optionalSoTotal;
  document.querySelector('[data-total-tokens="mandatory"]').textContent =
    mandatorySoTotal + mandatoryDocSize;
  document.querySelector('[data-total-tokens="optional"]').textContent =
    optionalSoTotal + optionalDocSize;
}

function updateOutputTokensTable() {
  const { mandatory, optional, mandatoryFields: mFields, optionalFields: oFields } =
    getColumnGroups();

  updateModelTableHeaders("output-tokens-table", "data-output-tokens-header");

  const thinkingPerPrompt = Number(thinkingBudgetPerPrompt.value) || 0;
  const mandatorySoOutputPerField =
    Number(mandatorySoOutputTokensPerField.value) || 0;
  const optionalSoOutputPerField =
    Number(optionalSoOutputTokensPerField.value) || 0;
  const mandatoryGrouping = Number(mandatoryGroupingFactor.value) || 0;
  const optionalGrouping = Number(optionalGroupingFactor.value) || 0;

  const mandatoryThinkingTotal =
    mFields > 0 ? thinkingPerPrompt * mandatory : 0;
  const optionalThinkingTotal =
    oFields > 0 ? thinkingPerPrompt * optional : 0;
  const mandatorySoOutputTotal =
    mFields > 0 ? mandatorySoOutputPerField * mandatoryGrouping * mandatory : 0;
  const optionalSoOutputTotal =
    oFields > 0 ? optionalSoOutputPerField * optionalGrouping * optional : 0;

  document.querySelector('[data-thinking-budget-total="mandatory"]').textContent =
    mandatoryThinkingTotal;
  document.querySelector('[data-thinking-budget-total="optional"]').textContent =
    optionalThinkingTotal;
  document.querySelector('[data-so-output-total="mandatory"]').textContent =
    mandatorySoOutputTotal;
  document.querySelector('[data-so-output-total="optional"]').textContent =
    optionalSoOutputTotal;
  document.querySelector('[data-output-total-tokens="mandatory"]').textContent =
    mandatoryThinkingTotal + mandatorySoOutputTotal;
  document.querySelector('[data-output-total-tokens="optional"]').textContent =
    optionalThinkingTotal + optionalSoOutputTotal;
}

function getPricingNumbers(modelId) {
  const pricing = PRICING[modelId];
  return {
    inputCost: Number(pricing.inputCost),
    inputCaching: Number(pricing.inputCaching),
    outputCost: Number(pricing.outputCost),
    outputCaching: Number(pricing.outputCaching),
  };
}

function getInputTotalTokens(groups, column, fieldCount) {
  if (fieldCount === 0) return 0;
  const soPerGroup = Number(soTokensPerGroup.value) || 0;
  const documentSize = columnReceivesDocumentSize(column)
    ? Number(documentSizeTokens.value) || 0
    : 0;
  return soPerGroup * groups + documentSize;
}

function getOutputTotalTokens(column, groups, fieldCount) {
  if (fieldCount === 0) return 0;
  const thinkingPerPrompt = Number(thinkingBudgetPerPrompt.value) || 0;
  const grouping =
    column === "mandatory"
      ? Number(mandatoryGroupingFactor.value) || 0
      : Number(optionalGroupingFactor.value) || 0;
  const soOutputPerField =
    column === "mandatory"
      ? Number(mandatorySoOutputTokensPerField.value) || 0
      : Number(optionalSoOutputTokensPerField.value) || 0;

  const thinkingTotal = thinkingPerPrompt * groups;
  const soOutputTotal = soOutputPerField * grouping * groups;
  return thinkingTotal + soOutputTotal;
}

function formatCost(amount) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 9,
  }).format(amount);
}

function setEstimatedCost(key, column, value) {
  document.querySelector(
    `[data-estimated-cost="${key}"][data-column-value="${column}"]`
  ).textContent = formatCost(value);
}

function updateExtractionSummary(invoicesMonthly, totalCostSum) {
  document.getElementById("extraction-invoices-monthly").textContent =
    new Intl.NumberFormat("en-US").format(invoicesMonthly);
  document.getElementById("extraction-total-cost").textContent =
    formatCost(totalCostSum);
}

function clearEstimatedCostColumn(column) {
  [
    "oneTimeInput",
    "promptInput",
    "cachedInput",
    "outputCost",
    "totalCostPerDocument",
    "inputCostTotal",
    "outputCostMonthly",
    "totalCost",
  ].forEach((key) => setEstimatedCost(key, column, 0));
}

function updateEstimatedCostTable() {
  updateModelTableHeaders("estimated-cost-table", "data-estimated-cost-header");

  const models = {
    mandatory: mandatoryModel.value,
    optional: optionalModel.value,
  };
  const { mandatory, optional } = getColumnGroups();
  const promptSize = Number(promptSizeTokens.value) || 0;
  const invoicesMonthly =
    (Number(invoicesDay.value) || 0) * (Number(workingDays.value) || 0);
  let totalCostSum = 0;

  ["mandatory", "optional"].forEach((column) => {
    const fieldCount = getFieldCount(column);
    if (fieldCount === 0) {
      clearEstimatedCostColumn(column);
      return;
    }

    const ocrCost = getOcrCostForColumn(column);
    const groups = column === "mandatory" ? mandatory : optional;
    const pricing = getPricingNumbers(models[column]);
    const inputTotalTokens = getInputTotalTokens(groups, column, fieldCount);
    const outputTotalTokens = getOutputTotalTokens(column, groups, fieldCount);

    const oneTimeInput = inputTotalTokens * pricing.inputCaching;
    const promptInput = promptSize * groups * pricing.inputCost;
    const cachedInput =
      groups * inputTotalTokens * pricing.outputCaching;
    const outputCost = outputTotalTokens * pricing.outputCost;

    const inputCostTotal =
      (oneTimeInput + promptInput + cachedInput) * invoicesMonthly;
    const outputCostMonthly = outputCost * invoicesMonthly;

    setEstimatedCost("oneTimeInput", column, oneTimeInput);
    setEstimatedCost("promptInput", column, promptInput);
    setEstimatedCost("cachedInput", column, cachedInput);
    setEstimatedCost("outputCost", column, outputCost);
    setEstimatedCost(
      "totalCostPerDocument",
      column,
      oneTimeInput + promptInput + cachedInput + outputCost
    );
    setEstimatedCost("inputCostTotal", column, inputCostTotal);
    setEstimatedCost("outputCostMonthly", column, outputCostMonthly);
    setEstimatedCost(
      "totalCost",
      column,
      inputCostTotal + outputCostMonthly + ocrCost
    );
    totalCostSum += inputCostTotal + outputCostMonthly + ocrCost;
  });

  updateExtractionSummary(invoicesMonthly, totalCostSum);
}

function updateStatisticsTable() {
  const day = Number(invoicesDay.value) || 0;
  const days = Number(workingDays.value) || 0;
  const mandatory = Number(mandatoryFields.value) || 0;
  const optional = Number(optionalFields.value) || 0;

  document.querySelector('[data-stat="invoices-monthly"]').textContent =
    day * days;
  document.querySelector('[data-stat="fields-total"]').textContent =
    mandatory + optional;

  updateColumnVisibility();
  updatePricingTable();
  updateInputTokensTable();
  updateOutputTokensTable();
  updateEstimatedCostTable();
}

function updateView() {
  updateStatisticsTable();
}

[
  invoicesDay,
  workingDays,
  documentSizeTokens,
  soTokensPerGroup,
  promptSizeTokens,
  thinkingBudgetPerPrompt,
  mandatorySoOutputTokensPerField,
  optionalSoOutputTokensPerField,
  mandatoryGroupingFactor,
  optionalGroupingFactor,
  mandatoryModel,
  optionalModel,
  mandatoryFields,
  optionalFields,
  mandatoryEstimatedOcrCost,
  optionalEstimatedOcrCost,
].forEach((control) => {
  control.addEventListener("input", updateView);
  control.addEventListener("change", updateView);
});

updateView();
initParamHints();
